name: Generate GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Stats Card
        uses: anuraghazra/github-readme-stats-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: omerglck
          output-dir: generated
          theme: tokyonight
          hide_border: true
          show_icons: true
          include_all_commits: true

      - name: Commit & Push SVGs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github stats [skip ci]"
